services:
  server:
    network_mode: bridge
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DISABLE_OPCACHE: "true"
    environment:
      - COMPOSE_BAKE=true
      - UPLOAD_MAX_FILESIZE=200M
    ports:
      - "8007:80"
    volumes:
      - ./:/var/www/html/